"""
This file contains a method to produce a surface mapping that includes the MISR, DTCL, and LS approaches for size
for a PT-specific case. Requires a surface mesh (ending in 'cl_mapped.vtp') with a 'taylor_len' array, generated by map_info.py.
Will produce a file called "proj_name_mapped.vtp" that has attributes "SizeDistanceToCenterlines" "SizeMISR" and "Size"
corresponding to the DTCL, MISR, and LS strategies respectively.

Call this script using:
map_DTCL_MISR.py proj_dir proj_name min_el max_el multi_inlets ref

Where 
-proj_dir is the directory where the surface mesh is stored,
-proj_name is the name you want all of your files to start with,
-min_el and max_el are your min and max edge lengths that you want,
-multi_inlets indicates whether there are more than one inlet (options are 'Multi' and 'single'),
-ref indicates if you want a refinement patch, defined as a mask in map_info.py, and is a float 
indicating the level of refinement (eg. 0.8) you want
"""

import numpy as np
import pyvista as pv
from geometry_tools.meshing import Mesher
import geometry_tools.vmtk_wrapper as vmtk
import geometry_tools.common as cc
from geometry_tools.make_submission_file import SubmissionTemplate
from scipy.interpolate import interp1d
from scipy.spatial import cKDTree as KDTree 
from pathlib import Path
import sys

def create_size_array(surf, min_el=0.2, max_el=0.7, ref='False'):
    min_tay=np.min(surf.point_data['taylor_len'])
    max_tay=np.max(surf.point_data['taylor_len'])
    interp = interp1d([min_tay, max_tay], [min_el, max_el], 
        kind='linear',
        bounds_error=False,
        fill_value=(min_el, max_el),
        )
    surf.point_data['Size'] = interp(surf.point_data['taylor_len'])
    if ref !='False':
        surf.point_data['Size'][surf.point_data['ref']==1]=float(ref)*surf.point_data['Size'][surf.point_data['ref']==1]
        surf, _ = cc.smooth_mesh_data_local(surf, array='Size', func=np.mean, iterations = 3)
    return surf

def map_surf(proj_dir, proj_name, min_el, max_el, multi_inlets,ref):
    if not proj_dir.exists():
        proj_dir.mkdir()
    main_dir = proj_dir.parent
    mapped_file = sorted(main_dir.glob('*_cl_mapped.vtp'))[0]
    new_surffile = proj_dir/(proj_name + '_mapped.vtp')

    surf=pv.read(mapped_file)
    m = Mesher(
            surf,
            include_aneurysms=False
            )
    m.centerlines = pv.read(main_dir/(proj_name.split('_')[0] +'_centerline.vtp'))
    m.surf, m.centerlines = vmtk.distance_to_centerlines(m.surf, m.centerlines)

    #DTCL approach
    dtcl_max = np.max(m.surf.point_data['DistanceToCenterlinesArray'])
    dtcl_min = np.min(m.surf.point_data['DistanceToCenterlinesArray'])
    m.surf.clean()
    #check for refinement points
    if ref != 'False':
        m.surf.point_data['RefinementPoints']=m.surf.point_data['ref']
    m.surf = cc.create_edge_size_array(m.surf, fix_centerline='reg', min_edge_size=min_el, max_edge_size=max_el, misr_min=dtcl_min, misr_max=dtcl_max)
    m.surf.clean()

    #MISR approach
    m.surf.point_data['centerline_map']=np.array(m.surf.n_points)
    m.surf.point_data['misr']=np.array(m.surf.n_points)
    tree = KDTree(m.centerlines.points)
    _, idx_c = tree.query(m.surf.points)
    #this assigns the closest centerline point id to each point on the surf
    m.surf.point_data['centerline_map']=idx_c 
    #this assigns the misr associated with the centerline to each point
    tree2 = KDTree(m.surf.points)
    dist, _ = tree2.query(m.centerlines.points) #closest dist to centerline point
    m.centerlines.point_data['MaximumInscribedSphereRadius']=dist
    m.surf.point_data['misr']=m.centerlines.point_data['MaximumInscribedSphereRadius'][idx_c] 
    #fix around the ends
    _, idx_d = tree.query(m.surf.points[m.surf.point_data['misr']==0], k=10)
    max_neigh_misr = np.amax(m.centerlines.point_data['MaximumInscribedSphereRadius'][idx_d], axis=1)
    m.surf.point_data['misr'][m.surf.point_data['misr']==0]=max_neigh_misr
    
    misr_max = np.max(m.surf.point_data['misr'])
    misr_min = np.min(m.surf.point_data['misr'])
    m.surf = cc.create_edge_size_array(m.surf, fix_centerline='fix', min_edge_size=min_el, max_edge_size=max_el, misr_min=misr_min, misr_max=misr_max)
    m.surf.clean()

    #My approach
    m.surf = create_size_array(m.surf, min_el=min_el, max_el=max_el, ref=ref)
    m.surf.clean()

    m.surf.save(new_surffile)

if __name__ == "__main__":
    proj_dir = Path(sys.argv[1]) 
    proj_name=sys.argv[2]
    min_el=sys.argv[3]
    max_el=sys.argv[4]
    multi_inlets = sys.argv[5]
    if len(sys.argv)>6:
        ref=sys.argv[6]
    else: 
        ref='False'
    map_surf(proj_dir=proj_dir, proj_name=proj_name, min_el=min_el, max_el=max_el, multi_inlets=multi_inlets, ref=ref)
